// Script generated by Dymola Mon Jul  6 20:35:08 2020
// Plot commands
removePlots(false);
Advanced.FilenameInLegend = true;
createPlot(id=1, position={12, 11, 534, 336}, y={"tSupSet.ySATsetpoint"}, range={0.0, 6000.0, 10.0, 40.0}, grid=true, colors={{28,108,200}}, displayUnits={"degC"});
createPlot(id=2, position={22, 392, 534, 259}, y={"tSupSet.SBC", "tSupSet.SBH"}, range={0.0, 6000.0, -0.2, 1.2000000000000002}, grid=true, colors={{28,108,200}, {28,108,200}});
createPlot(id=3, position={574, 15, 534, 336}, y={"tSupSet.totCoolReqs"}, range={0.0, 6000.0, -1.0, 9.0}, grid=true, colors={{28,108,200}});

// Non-standard flags
Advanced.FilenameInLegend = true;
Advanced.IncludeNonGraphical = true;
// Variables 
experiment startTime=0 stopTime=5760 tolerance=0.0001 numberOfIntervals=500
tSupSet.conPI.k=3;
tSupSet.conPI.Ti=300;
tSupSet.conPI.Td=0.1;
tSupSet.conPI.yMax=1;
tSupSet.conPI.yMin=0;
tSupSet.conPI.wp=1.5;
tSupSet.conPI.wd=0;
tSupSet.conPI.Ni=0.9;
tSupSet.conPI.Nd=10;
tSupSet.conPI.xi_start=0;
tSupSet.conPI.yd_start=0;
tSupSet.conPI.reverseAction=true;
tSupSet.X1.k=0;
tSupSet.X2.k=1;
tSupSet.subtract.k1=-1;
tSupSet.subtract.k2=1;
tSupSet.fixedOffset.k=10;
tSupSet.minSATset=287.15;
tSupSet.maxSATset=292.15;
tSupSet.HeatSet=308.15;
tSupSet.TUpcntT=0.15;
totCoolReqsGen.y_start=0;
booPul3.width=0.25;
booPul3.period=680;
booPul3.startTime=1000;
con.k=false;
conInt.k=30;
highSpaceTGen.amplitude=5;
highSpaceTGen.freqHz=0.000277777777777778;
highSpaceTGen.phase=0;
highSpaceTGen.offset=300.15;
highSpaceTGen.startTime=0;
booPul1.width=0.875;
booPul1.period=1440;
booPul1.startTime=2160;
booPul2.width=0.275;
booPul2.period=1440;
booPul2.startTime=440;
