''' 
Plotting of Time Series
=======================

This module provide an example that illustrates the
use of the python to plot results from a Dymola simulation.

The file ``plotResult.py`` illustrates how to plot results from a
Dymola output file. To run the example, proceed as follows:

 1. Open a terminal or dos-shell.
 2. Set the PYTHONPATH environment variables to the 
    directory ```bie/BuildingsPy/buildingspy```, such as

    .. code-block:: bash

       export PYTHONPATH=${PYTHONPATH}:../..

    where the directory ``../..`` contains the subdirectory ``buildingspy``
 3. Type

    .. code-block:: bash

       python plotResult.py

This will execute the script ``plotResult.py``, which contains
the following instructions:

.. literalinclude:: ../../buildingspy/examples/dymolaplot/plotResult.py

The script generates the following plot:

.. image:: ../../buildingspy/examples/dymolaplot/plot.png
   :scale: 100 %
   :alt: Plot generated by ``plotResult.py``
   :align: center



'''

