within Buildings.Experimental.DHC.Loads.HotWater.Examples;
model HeaterAndFixtureDirectHeatExchangerWithAuxHeat
  extends Modelica.Icons.Example;
  extends BaseClasses.partialHeaterAndFixture(
    souCol(nPorts=2),
    souDis(nPorts=1),
    sinDis(nPorts=1));
  DirectHeatExchangerWithAuxHeat gen(
    redeclare package Medium = Medium,
                                     mHot_flow_nominal=mHot_flow_nominal,
      mDis_flow_nominal=mDis_flow_nominal)
    "Hot water generated by heat exchanger and auxiliary heat"
    annotation (Placement(transformation(extent={{-50,-10},{-30,10}})));
equation

  connect(gen.port_b1, tmv.port_hot) annotation (Line(points={{-30,6},{-10,6},{
          -10,4},{0,4}}, color={0,127,255}));
  connect(gen.port_a1, souCol.ports[2]) annotation (Line(points={{-50,6},{-60,6},
          {-60,-20},{10,-20},{10,-40}}, color={0,127,255}));
  connect(gen.port_a2, souDis.ports[1]) annotation (Line(points={{-30,-6},{-20,
          -6},{-20,-32},{-30,-32},{-30,-40}}, color={0,127,255}));
  connect(gen.port_b2, sinDis.ports[1])
    annotation (Line(points={{-50,-6},{-70,-6},{-70,-40}}, color={0,127,255}));
  connect(conTSetHot.y, gen.TSetHw)
    annotation (Line(points={{-79,0},{-51,0}}, color={0,0,127}));
  connect(gen.PHea, PEle) annotation (Line(points={{-29,0},{-20,0},{-20,80},{
          110,80}}, color={0,0,127}));
  annotation (experiment(
      StopTime=86400,
      Interval=1,
      Tolerance=1e-06,
      __Dymola_Algorithm="Dassl"));
end HeaterAndFixtureDirectHeatExchangerWithAuxHeat;
