within Buildings.Controls.OBC.DemandFlexibility.ZoneSetpointControl.Subsequences;
package BaseTemperatureSetpointElements
  extends Modelica.Icons.VariantsPackage;
end BaseTemperatureSetpointElements;
