within Buildings.Templates.Plants.Chillers.Components.Validation.Configuration;
record Variable1OnlyAirCooledParallel
  "Default configuration parameters for primary-only parallel air-cooled chiller plant"
  extends Buildings.Templates.Plants.Chillers.Configuration.ChillerPlant(
    cpChiWat_default=Buildings.Utilities.Psychrometrics.Constants.cpWatLiq,
    cpCon_default=Buildings.Utilities.Psychrometrics.Constants.cpAir,
    have_pumChiWatPriVar=true,
    have_pumChiWatSec=false,
    have_senDpChiWatRemWir=false,
    have_senLevCoo=false,
    have_senVChiWatSec=false,
    have_valChiWatChiBypPar=false,
    have_pumChiWatPriVarCom=true,
    have_pumConWatVarCom=false,
    have_pumConWatVar=false,
    nAirHan=0,
    nCoo=0,
    nEquZon=0,
    nLooChiWatSec=1,
    nPumChiWatPri=nChi,
    nPumChiWatSec=0,
    nPumConWat=0,
    nSenDpChiWatRem=1,
    rhoChiWat_default=Buildings.Media.Water.d_const,
    rhoCon_default=Buildings.Media.Air.dStp,
    typArrChi=Buildings.Templates.Plants.Chillers.Types.ChillerArrangement.Parallel,
    typArrPumChiWatPri=Buildings.Templates.Components.Types.PumpArrangement.Headered,
    typArrPumConWat=Buildings.Templates.Components.Types.PumpArrangement.Headered,
    typChi=Buildings.Templates.Components.Types.Chiller.AirCooled,
    typCoo=Buildings.Templates.Components.Types.Cooler.None,
    typCtl=Buildings.Templates.Plants.Chillers.Types.Controller.OpenLoop,
    typCtlHea=Buildings.Templates.Plants.Chillers.Types.ChillerLiftControl.None,
    typDisChiWat=Buildings.Templates.Plants.Chillers.Types.Distribution.Variable1Only,
    typEco=Buildings.Templates.Plants.Chillers.Types.Economizer.None,
    typMeaCtlChiWatPri=Buildings.Templates.Plants.Chillers.Types.PrimaryOverflowMeasurement.TemperatureSupplySensor,
    typValChiWatChiIso=Buildings.Templates.Components.Types.Valve.TwoWayTwoPosition,
    typValConWatChiIso=Buildings.Templates.Components.Types.Valve.None,
    typValCooInlIso=Buildings.Templates.Components.Types.Valve.None,
    typValCooOutIso=Buildings.Templates.Components.Types.Valve.None);
end Variable1OnlyAirCooledParallel;
