within Buildings.ThermalZones.EnergyPlus;
package UsersGuide
  "EnergyPlus package user's guide"
  extends Modelica.Icons.Information;

class SupportedOutputVariables "Supported output variables"
  extends ModelicaReference.Icons.Information;

  annotation (
preferredView="info",
Documentation(info="<html>
<h4>Overview</h4>
<p>
Using the model
<a href=\"Buildings.ThermalZones.EnergyPlus.OutputVariable\">Buildings.ThermalZones.EnergyPlus.OutputVariable</a>,
the current values of EnergyPlus output variables can be read into the Modelica model.
The table below shows all output variables supported by Spawn.
Which of these are available for a particular model depends on the EnergyPlus
idf-file. To list the output variables that are available in your model, add the line
</p>
<pre>
Output:VariableDictionary, IDF;
</pre>
<p>
to the EnergyPlus idf-file. This will produce an EnergyPlus result data dictionary (rdd) file.
</p>
<h4>List of supported output variables</h4>
<p>
The table below lists the output variables. The name in the first column
must be used as the value for the parameter <code>name</code>
in instances of
<a href=\"Buildings.ThermalZones.EnergyPlus.OutputVariable\">
Buildings.ThermalZones.EnergyPlus.OutputVariable</a>.
</p>
<!-- Start of table of output variables generated by install.py. Do not edit. -->
<table summary=\"Supported output variables\" border=\"1\" cellspacing=\"0\" cellpadding=\"2\" style=\"border-collapse:collapse;\">
<tr><th><code>OneZoneOneOutputVariable.name</code></th>     <th>Unit as received in Modelica</th> <th>Unit used by EnergyPlus</th> </tr>
 <tr>
  <td>Debug Surface Solar Shading Model DifShdgRatioHoriz</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Debug Surface Solar Shading Model DifShdgRatioIsoSky</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Debug Surface Solar Shading Model WithShdgIsoSky</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Debug Surface Solar Shading Model WoShdgIsoSky</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Electric Equipment Convective Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Electric Equipment Convective Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Electric Equipment Electric Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Electric Equipment Electric Power</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Electric Equipment Latent Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Electric Equipment Latent Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Electric Equipment Lost Heat Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Electric Equipment Lost Heat Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Electric Equipment Radiant Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Electric Equipment Radiant Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Electric Equipment Total Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Electric Equipment Total Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Environmental Impact Electricity CH4 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity CO Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity CO2 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity Hg Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity N2O Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity NH3 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity NMVOC Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity NOx Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity Nuclear High Level Waste Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity Nuclear Low Level Waste Volume</td>
  <td>m3</td>  <td>m3</td>
  </tr> <tr>
  <td>Environmental Impact Electricity PM Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity PM10 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity PM2.5 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity Pb Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity SO2 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Electricity Source Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Environmental Impact Electricity Water Consumption Volume</td>
  <td>m3</td>  <td>L</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas CH4 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas CO Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas CO2 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas Hg Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas N2O Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas NH3 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas NMVOC Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas NOx Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas Nuclear High Level Waste Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas Nuclear Low Level Waste Volume</td>
  <td>m3</td>  <td>m3</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas PM Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas PM10 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas PM2.5 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas Pb Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas SO2 Emissions Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas Source Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Environmental Impact Natural Gas Water Consumption Volume</td>
  <td>m3</td>  <td>L</td>
  </tr> <tr>
  <td>Environmental Impact Purchased Electricity Source Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Environmental Impact Surplus Sold Electricity Source</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Environmental Impact Total CH4 Emissions Carbon Equivalent Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Total CO2 Emissions Carbon Equivalent Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Environmental Impact Total N2O Emissions Carbon Equivalent Mass</td>
  <td>Kg</td>  <td>Kg</td>
  </tr> <tr>
  <td>Exterior Lights Electric Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Exterior Lights Electric Power</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Facility Cooling Setpoint Not Met Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Facility Cooling Setpoint Not Met While Occupied Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Facility Heating Setpoint Not Met Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Facility Heating Setpoint Not Met While Occupied Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Facility Thermal Comfort ASHRAE 55 Simple Model Summer Clothes Not Comfortable Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Facility Thermal Comfort ASHRAE 55 Simple Model Summer or Winter Clothes Not Comfortable Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Facility Thermal Comfort ASHRAE 55 Simple Model Winter Clothes Not Comfortable Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Lights Convective Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Lights Convective Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Lights Electric Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Lights Electric Power</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Lights Radiant Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Lights Radiant Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Lights Return Air Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Lights Return Air Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Lights Total Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Lights Total Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Lights Visible Radiation Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Lights Visible Radiation Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>People Air Relative Humidity</td>
  <td>1</td>  <td>%</td>
  </tr> <tr>
  <td>People Air Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>People Convective Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>People Convective Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>People Latent Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>People Latent Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>People Occupant Count</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>People Radiant Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>People Radiant Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>People Sensible Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>People Sensible Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>People Total Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>People Total Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Schedule Value</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Site Beam Solar Radiation Luminous Efficacy</td>
  <td>lm/W</td>  <td>lm/W</td>
  </tr> <tr>
  <td>Site Day Type Index</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Site Daylight Saving Time Status</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Site Daylighting Model Sky Brightness</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Site Daylighting Model Sky Clearness</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Site Deep Ground Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Diffuse Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Site Direct Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Site Exterior Beam Normal Illuminance</td>
  <td>lm/m2</td>  <td>lux</td>
  </tr> <tr>
  <td>Site Exterior Horizontal Beam Illuminance</td>
  <td>lm/m2</td>  <td>lux</td>
  </tr> <tr>
  <td>Site Exterior Horizontal Sky Illuminance</td>
  <td>lm/m2</td>  <td>lux</td>
  </tr> <tr>
  <td>Site Ground Reflected Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Site Ground Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Horizontal Infrared Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Site Mains Water Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Outdoor Air Barometric Pressure</td>
  <td>Pa</td>  <td>Pa</td>
  </tr> <tr>
  <td>Site Outdoor Air Density</td>
  <td>kg/m3</td>  <td>kg/m3</td>
  </tr> <tr>
  <td>Site Outdoor Air Dewpoint Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Outdoor Air Drybulb Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Outdoor Air Enthalpy</td>
  <td>J/kg</td>  <td>J/kg</td>
  </tr> <tr>
  <td>Site Outdoor Air Humidity Ratio</td>
  <td>1</td>  <td>kgWater/kgDryAir</td>
  </tr> <tr>
  <td>Site Outdoor Air Relative Humidity</td>
  <td>1</td>  <td>%</td>
  </tr> <tr>
  <td>Site Outdoor Air Wetbulb Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Precipitation Depth</td>
  <td>m</td>  <td>m</td>
  </tr> <tr>
  <td>Site Rain Status</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Site Simple Factor Model Ground Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Sky Diffuse Solar Radiation Luminous Efficacy</td>
  <td>lm/W</td>  <td>lm/W</td>
  </tr> <tr>
  <td>Site Sky Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Snow on Ground Status</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Site Solar Altitude Angle</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Site Solar Azimuth Angle</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Site Solar Hour Angle</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Site Surface Ground Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Site Total Surface Heat Emission to Air</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Site Total Zone Exfiltration Heat Loss</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Site Total Zone Exhaust Air Heat Loss</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Site Wind Direction</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Site Wind Speed</td>
  <td>m/s</td>  <td>m/s</td>
  </tr> <tr>
  <td>Surface Anisotropic Sky Multiplier</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Average Face Conduction Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Average Face Conduction Heat Loss Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Average Face Conduction Heat Transfer Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Average Face Conduction Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Average Face Conduction Heat Transfer Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Heat Storage Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Heat Storage Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Heat Storage Loss Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Heat Storage Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Heat Storage Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Absorbed Shortwave Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Adjacent Air Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Surface Inside Face Beam Solar Radiation Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Conduction Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Conduction Heat Loss Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Conduction Heat Transfer Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face Conduction Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Conduction Heat Transfer Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Convection Classification Index</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Inside Face Convection Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face Convection Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Convection Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Convection Heat Transfer Coefficient</td>
  <td>W/m2-K</td>  <td>W/m2-K</td>
  </tr> <tr>
  <td>Surface Inside Face Convection Model Equation Index</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Inside Face Convection Reference Air Index</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Inside Face Exterior Windows Incident Beam Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face Exterior Windows Incident Beam Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Exterior Windows Incident Beam Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Heat Source Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Initial Transmitted Diffuse Absorbed Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Initial Transmitted Diffuse Transmitted Out Window Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Interior Movable Insulation Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Surface Inside Face Interior Windows Incident Beam Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face Interior Windows Incident Beam Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Interior Windows Incident Beam Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Internal Gains Radiation Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face Internal Gains Radiation Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Internal Gains Radiation Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Lights Radiation Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face Lights Radiation Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Lights Radiation Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Net Surface Thermal Radiation Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face Net Surface Thermal Radiation Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Net Surface Thermal Radiation Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Solar Radiation Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face Solar Radiation Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face Solar Radiation Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face System Radiation Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Inside Face System Radiation Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Inside Face System Radiation Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Inside Face Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Surface Outside Face Beam Solar Incident Angle Cosine Value</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Outside Face Conduction Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Outside Face Conduction Heat Loss Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Outside Face Conduction Heat Transfer Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Outside Face Conduction Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Outside Face Conduction Heat Transfer Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Convection Classification Index</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Outside Face Convection Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Outside Face Convection Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Outside Face Convection Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Convection Heat Transfer Coefficient</td>
  <td>W/m2-K</td>  <td>W/m2-K</td>
  </tr> <tr>
  <td>Surface Outside Face Forced Convection Model Equation Index</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Outside Face Heat Emission to Air Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Outside Face Heat Source Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Beam Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Beam To Beam Surface Reflected Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Beam To Diffuse Ground Reflected Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Beam To Diffuse Surface Reflected Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Ground Diffuse Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Sky Diffuse Ground Reflected Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Sky Diffuse Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Sky Diffuse Surface Reflected Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Incident Solar Radiation Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Natural Convection Model Equation Index</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Outside Face Net Thermal Radiation Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Outside Face Net Thermal Radiation Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Outside Face Net Thermal Radiation Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Outdoor Air Drybulb Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Surface Outside Face Outdoor Air Wetbulb Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Surface Outside Face Outdoor Air Wind Direction</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Surface Outside Face Outdoor Air Wind Speed</td>
  <td>m/s</td>  <td>m/s</td>
  </tr> <tr>
  <td>Surface Outside Face Solar Radiation Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Outside Face Solar Radiation Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Outside Face Solar Radiation Heat Gain Rate per Area</td>
  <td>W/m2</td>  <td>W/m2</td>
  </tr> <tr>
  <td>Surface Outside Face Sunlit Area</td>
  <td>m2</td>  <td>m2</td>
  </tr> <tr>
  <td>Surface Outside Face Sunlit Fraction</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Outside Face Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Surface Outside Face Thermal Radiation to Air Heat Transfer Coefficient</td>
  <td>W/m2-K</td>  <td>W/m2-K</td>
  </tr> <tr>
  <td>Surface Outside Face Thermal Radiation to Air Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Outside Face Thermal Radiation to Ground Heat Transfer Coefficient</td>
  <td>W/m2-K</td>  <td>W/m2-K</td>
  </tr> <tr>
  <td>Surface Outside Face Thermal Radiation to Sky Heat Transfer Coefficient</td>
  <td>W/m2-K</td>  <td>W/m2-K</td>
  </tr> <tr>
  <td>Surface Outside Normal Azimuth Angle</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Surface Shading Device Is On Time Fraction</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Storm Window On Off Status</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window BSDF Beam Direction Number</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window BSDF Beam Phi Angle</td>
  <td>rad</td>  <td>rad</td>
  </tr> <tr>
  <td>Surface Window BSDF Beam Theta Angle</td>
  <td>rad</td>  <td>rad</td>
  </tr> <tr>
  <td>Surface Window Back Face Temperature Layer 1</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Surface Window Blind Slat Angle</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Surface Window Front Face Temperature Layer 1</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Surface Window Gap Convective Heat Transfer Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Gap Convective Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Glazing Beam to Beam Solar Transmittance</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window Glazing Beam to Diffuse Solar Transmittance</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window Glazing Diffuse to Diffuse Solar Transmittance</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Heat Loss Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Heat Loss Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Inside Face Divider Condensation Status</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window Inside Face Frame Condensation Status</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window Inside Face Glazing Condensation Status</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window Model Solver Iteration Count</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window Net Heat Transfer Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Net Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Outside Reveal Reflected Beam Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Outside Reveal Reflected Beam Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Shading Device Absorbed Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Shading Device Absorbed Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Solar Horizontal Profile Angle</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Surface Window Solar Vertical Profile Angle</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Surface Window System Solar Absorptance</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window System Solar Reflectance</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window System Solar Transmittance</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Surface Window Total Glazing Layers Absorbed Shortwave Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Total Glazing Layers Absorbed Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Total Glazing Layers Absorbed Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Transmitted Beam Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Transmitted Beam Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Transmitted Beam To Beam Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Transmitted Beam To Beam Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Transmitted Beam To Diffuse Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Transmitted Beam To Diffuse Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Transmitted Diffuse Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Transmitted Diffuse Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Surface Window Transmitted Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Surface Window Transmitted Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Air Heat Balance Air Energy Storage Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Air Heat Balance Internal Convective Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Air Heat Balance Interzone Air Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Air Heat Balance Outdoor Air Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Air Heat Balance Surface Convection Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Air Heat Balance System Air Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Air Heat Balance System Convective Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Cooling Setpoint Not Met Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Zone Cooling Setpoint Not Met While Occupied Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Zone Electric Equipment Convective Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Electric Equipment Convective Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Electric Equipment Electric Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Electric Equipment Electric Power</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Electric Equipment Latent Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Electric Equipment Latent Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Electric Equipment Lost Heat Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Electric Equipment Lost Heat Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Electric Equipment Radiant Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Electric Equipment Radiant Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Electric Equipment Total Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Electric Equipment Total Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Exfiltration Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Exfiltration Latent Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Exfiltration Sensible Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Exhaust Air Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Exhaust Air Latent Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Exhaust Air Sensible Heat Transfer Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Exterior Windows Total Transmitted Beam Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Exterior Windows Total Transmitted Beam Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Exterior Windows Total Transmitted Diffuse Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Exterior Windows Total Transmitted Diffuse Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Heating Setpoint Not Met Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Zone Heating Setpoint Not Met While Occupied Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Zone Interior Windows Total Transmitted Beam Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Interior Windows Total Transmitted Beam Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Interior Windows Total Transmitted Diffuse Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Interior Windows Total Transmitted Diffuse Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Lights Convective Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Lights Convective Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Lights Electric Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Lights Electric Power</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Lights Radiant Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Lights Radiant Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Lights Return Air Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Lights Return Air Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Lights Total Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Lights Total Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Lights Visible Radiation Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Lights Visible Radiation Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Mean Air Dewpoint Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Mean Air Humidity Ratio</td>
  <td>1</td>  <td>kgWater/kgDryAir</td>
  </tr> <tr>
  <td>Zone Mean Air Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Mean Radiant Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Operative Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Outdoor Air Drybulb Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Outdoor Air Wetbulb Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Outdoor Air Wind Direction</td>
  <td>rad</td>  <td>deg</td>
  </tr> <tr>
  <td>Zone Outdoor Air Wind Speed</td>
  <td>m/s</td>  <td>m/s</td>
  </tr> <tr>
  <td>Zone People Convective Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone People Convective Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone People Latent Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone People Latent Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone People Occupant Count</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Zone People Radiant Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone People Radiant Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone People Sensible Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone People Sensible Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone People Total Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone People Total Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Thermal Comfort ASHRAE 55 Simple Model Summer Clothes Not Comfortable Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Zone Thermal Comfort ASHRAE 55 Simple Model Summer or Winter Clothes Not Comfortable Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Zone Thermal Comfort ASHRAE 55 Simple Model Winter Clothes Not Comfortable Time</td>
  <td>s</td>  <td>hr</td>
  </tr> <tr>
  <td>Zone Thermal Comfort Clothing Surface Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Thermal Comfort Fanger Model PMV</td>
  <td>1</td>  <td>1</td>
  </tr> <tr>
  <td>Zone Thermal Comfort Fanger Model PPD</td>
  <td>1</td>  <td>%</td>
  </tr> <tr>
  <td>Zone Thermal Comfort Mean Radiant Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Thermal Comfort Operative Temperature</td>
  <td>K</td>  <td>C</td>
  </tr> <tr>
  <td>Zone Total Internal Convective Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Total Internal Convective Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Total Internal Latent Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Total Internal Latent Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Total Internal Radiant Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Total Internal Radiant Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Total Internal Total Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Total Internal Total Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Total Internal Visible Radiation Heating Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Total Internal Visible Radiation Heating Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Windows Total Heat Gain Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Windows Total Heat Gain Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Windows Total Heat Loss Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Windows Total Heat Loss Rate</td>
  <td>W</td>  <td>W</td>
  </tr> <tr>
  <td>Zone Windows Total Transmitted Solar Radiation Energy</td>
  <td>J</td>  <td>J</td>
  </tr> <tr>
  <td>Zone Windows Total Transmitted Solar Radiation Rate</td>
  <td>W</td>  <td>W</td>
  </tr>
</table>
<!-- End of table of output variables generated by install.py. Do not edit. -->
</html>"));
end SupportedOutputVariables;
  annotation (
    preferredView="info",
    Documentation(
      info="<html>
<h4>Overview</h4>
<p align=\"right\">
<img alt=\"Spawn logo\" src=\"modelica://Buildings/Resources/Images/ThermalZones/EnergyPlus/spawn_icon_darkbluetxlowres.png\"  style=\"float:right;height=203px;width:587px;\"/>
</p>
<p>
This user guide describes how to use the EnergyPlus building envelope model.
</p>
<p>
Currently Windows 64 bit and Linux 64 bit are supported.
</p>
<p>
To instanciate one or several buildnig models, proceed as follows:
</p>
<ol>
<li>
Create an instance of
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.Building\">
Buildings.ThermalZones.EnergyPlus.Building</a> to specify the building model.
This instance is automatically named <code>building</code> and this
name must not be changed.<br/>
</li>
<li>
In the instance <code>building</code>, specify building-level parameters such as the
EnergyPlus input file name and weather file name.
</li>
<li>
For the weather file, both <code>.mos</code> and <code>.epw</code> files
must be provided in the same directory. The files must have the same name, except
for the different extension.
The <code>.epw</code> file will be used by the EnergyPlus envelope model, and the <code>.mos</code>
file will be used by the Modelica model, and must be specified by the parameter <code>weaName</code>
in the instance <code>building</code>.
</li>
<li>
In the model that contains the instance <code>building</code>,
or in any model instanciated by that model, instantiate
for each thermal zone an instance of
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.ThermalZone\">
Buildings.ThermalZones.EnergyPlus.ThermalZone</a>.
These thermal zones will automatically be assigned the name of the
EnergyPlus input data file and weather file, as well as the other parameters
that are declared in the instance <code>building</code>.
In these instances, specify the name of the thermal zone, as it is entered
in the EnergyPlus input data file, and also assign the medium of the thermal zone,
as is done for any other fluid flow component.
This instance will then connect the Modelica zone model with the
EnergyPlus zone model.
</li>
<li>
Optionally, to write to EnergyPlus actuators or schedules during the simulation,
instantiate any number of
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.Actuator\">
Buildings.ThermalZones.EnergyPlus.Actuator</a>
or
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.Schedule\">
Buildings.ThermalZones.EnergyPlus.Schedule</a> models.
</li>
<li>
Optionally, to retrieve the current values of output variables from EnergyPlus,
instantiate any number of
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.OutputVariable\">
Buildings.ThermalZones.EnergyPlus.OutputVariable</a> models.
</li>
</ol>
<p>
If you have more than one building, then repeat the above steps for each building and combine
these building models in a top-level model.
See for example
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.Validation.MultipleBuildings.ThreeZonesTwoBuildings\">
Buildings.ThermalZones.EnergyPlus.Validation.MultipleBuildings.ThreeZonesTwoBuildings</a>
for how to combine two buildings in one Modelica model.
</p>
<p>
For details of how to configure these models, see the information section of these models.
</p>
<h4>Conventions</h4>
<p>
The following conventions are made:
</p>
<ul>
<li>
All zones in the idf file must have a zone model in Modelica. Otherwise
the simulation stops with an error.
</li>
<li>
If there is an HVAC system in the idf file, then EnergyPlus issues a warning,
the EnergyPlus HVAC system is not simulated, but the coupled EnergyPlus/Modelica
simulation proceeds.
</li>
<li>
For the EnergyPlus envelope, either the CTF transfer function or the finite difference
method can be used.
</li>
<li>
The coupling time step is determined by EnergyPlus based on the zone time step,
as declared in the idf file.
</li>
</ul>
<!-- .................................................................... -->
<h4>Unit conversion</h4>
<p>
Units between Modelica and EnergyPlus are automatically converted, if they are specified.
The conversion is according to the table at
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.Types.Units\">
Buildings.ThermalZones.EnergyPlus.Types.Units</a>.
</p>
<p>
To see what units are used, set <code>printUnits=true</code> (the default) in the
instance
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.Building\">
Buildings.ThermalZones.EnergyPlus.Building</a>.
This will cause the used units to be reported in the Modelica log file.
</p>
<p>
The thermal zone model automatically converts the units.
</p>
<p>
To do unit conversion for values sent by
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.Actuator\">
Buildings.ThermalZones.EnergyPlus.Actuator</a>
and by
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.Schedule\">
Buildings.ThermalZones.EnergyPlus.Schedule</a>,
set the parameter <code>unit</code> to the unit of the variable obtained at
the input connector <code>u</code>. The value will then be converted
before it is sent to EnergyPlus.
The units that are used in the input <code>u</code> of this block
are reported to the Modelica log file.
</p>
<p>
To do unit conversion for values read by
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.OutputVariable\">
Buildings.ThermalZones.EnergyPlus.OutputVariable</a>,
Modelica will use the units reported by EnergyPlus.
The units that are used in the output <code>y</code> of this block
are reported to the Modelica log file.
</p>
<!-- .................................................................... -->
<h4>EnergyPlus warm-up</h4>
<p>
In Spawn there can be both connected and unconnected zones defined in the EnergyPlus input file.
Connected zones have a corresponding zone model
<a href=\"modelica://Buildings.ThermalZones.EnergyPlus.ThermalZone\">
Buildings.ThermalZones.EnergyPlus.ThermalZone</a>
in Modelica that communicates with the EnergyPlus zone heat balance model.
Unconnected zones are thermal zones which are defined entirely within the EnergyPlus input file,
and for these zones the conventional EnergyPlus algorithms are used to simulate the zone conditions,
including the air temperature and humidity, which are free floating.
In contrast, for connected zones, Modelica models the temperature and humidity.
During the initialization of a new simulation it is necessary to compute initial values
for the zone air conditions as well as the conditions of any thermal mass, such as for walls, floors and ceilings.
Conventionally, EnergyPlus handles this requirement using a warmup period,
and in Spawn the traditional EnergyPlus warmup algorithm is employed
to initialize unconnected zones.
The EnergyPlus warmup algorithm is described in the
<a href=\"https://bigladdersoftware.com/epx/docs/9-3/engineering-reference/warmup-convergence.html#warmup-convergence\">
EnergyPlus Engineering Reference</a>, and summarized in the following steps.
</p>
<ol>
<li>
<p>
Zone and wall surface temperatures are initialized to <i>23</i>&deg;C.
</p>
</li>
<li>
<p>
Zone humidity ratios are initialized to the outdoor conditions.
</p>
</li>
<li>
<p>
During warmup, the outdoor conditions are determined by the EnergyPlus weather file.
</p>
</li>
<li>
<p>
The first day of the simulation is repeated until warmup convergence,
which occurs when the minimum and maximum air temperatures during the warmup day
remain nearly the same between two successive iterations.
</p>
</li>
</ol>
<p>
Spawn initializes unconnected zones using the warmup algorithm that was just described.
However, connected zones are treated differently than in a conventional EnergyPlus simulation
because initial zone air properties are specified in the Modelica zone model.
During Spawn warmup, the following steps occur:
</p>
<ol>
<li>
<p>
All wall surface temperatures are initialized to <i>23</i>&deg;C
just as they are in a conventional EnergyPlus warmup period.
However, as in EnergyPlus, during the warmup iterations,
the exterior walls will be subject to the ambient conditions defined by the weather file.
Therefore, exterior surface temperatures will not remain fixed at their <i>23</i>&deg;C
initial condition during the warmup process.
Similarly, room-facing wall surfaces will be exposed to the zone temperature, and
therefore approach a quasi-steady state at the conclusion of warmup.
</p>
</li>
<li>
<p>
The air temperatures of unconnected zones are initialized to <i>23</i>&deg;C.
</p>
</li>
<li>
<p>
The humidity ratios of unconnected zones are initialized to the outdoor conditions.
</p>
</li>
<li>
<p>
The air temperatures and humidity ratios of connected zones are initialized to
the initial values defined in Modelica, and held fixed during the warmup period.
</p>
</li>
<li>
<p>
During warmup, the outdoor conditions are determined by the EnergyPlus weather file
in the same way as a conventional EnergyPlus simulation.
</p>
</li>
<li>
<p>
The first day of the simulation is repeated until the minimum and maximum air temperatures
during the warmup day remain nearly the same between two successive iterations.
</p>
</li>
</ol>
<p>
The Spawn warmup procedure is still invoked even if there are no unconnected zones defined in the model.
However, in this case the warmup convergence criteria will be met after only two iterations of the warmup day
because all zone temperature and humidity values are fixed to the initial values defined in Modelica.
It is possible for startup transients to still exist after Spawn warmup due thermal mass
in the wall materials not being fully exposed to the surface boundary conditions
defined by the outdoor environment and the initial zone air conditions.
A future enhancement may define a new warmup convergence criteria that takes into account
the internal wall temperatures.
</p>
<!-- .................................................................... -->
<h4>Notes for Dymola</h4>
<h5>64 bit configuration</h5>
<p>
Make sure Dymola compiles in 64 bit, which can be done by setting the flag
</p>
<pre>
Advanced.CompileWith64 = 2
</pre>
<p>
Otherwise, you may get an error such as
</p>
<pre>
/usr/bin/ld: cannot find -lfmilib_shared
collect2: error: ld returned 1 exit status
</pre>
<h5>Models with multiple thermal zones</h5>
<p>
For Dymola 2019FD01 and Dymola 2020, only one thermal zone can be in EnergyPlus.
For Dymola 2020x, this limitation is removed if the flag
</p>
<pre>
Hidden.AvoidDoubleComputation=true
</pre>
<p>
is set in the Dymola command line window.
For Dymola 2021, this flag will be set to <code>true</code> by default.
</p>
<p>
This limitation only affects Dymola. OPTIMICA and JModelica can simulate Modelica models
for which the EnergyPlus model has multiple thermal zones, or for which
multiple buildings are simulated in EnergyPlus.
</p>
</html>",
      revisions="<html>
<ul>
<li>
April 20, 2020, by Kun Zhang: <br/>
Added note for weather file.
</li>
<li>
August 26, 2019, by Michael Wetter:<br/>
Added note about Dymola (Dassault Service Request SR00584808).
</li>
<li>
May 22, 2019, by Michael Wetter:<br/>
Created User's guide.
</li>
</ul>
</html>"));
end UsersGuide;
