within Buildings.Fluid.HeatPumps.Data.ScrollWaterToWater.Heating;
record Carrier_50PSW122_38kW_4_29COP_R410A =
  Buildings.Fluid.HeatPumps.Data.ScrollWaterToWater.Generic (
    volRat = 1.81466473546,
    V_flow_nominal = 0.00670253502001,
    leaCoe = 0.00764809592483,
    etaEle = 1.0,
    PLos = 1881.76772552,
    dTSup = 2.96952832147e-16,
    UACon = 9021.05488178,
    UAEva = 7132.41759701)

  annotation (
    defaultComponentPrefixes = "parameter",
    defaultComponentName="datHeaPum",
    preferredView="info",
  Documentation(info="<html>
<p>
Generated by M. Cimmino on 2017-01-26.
</p>
</html>"));
