within Buildings.Fluid.HeatPumps.Data.ScrollWaterToWater.Heating;
record Daikin_WRA060_19kW_4_50COP_R410A =
  Buildings.Fluid.HeatPumps.Data.ScrollWaterToWater.Generic (
    volRat = 2.02058512825,
    V_flow_nominal = 0.00203948729471,
    leaCoe = 0.00265331062627,
    etaEle = 0.818648566096,
    PLos = 834.025033052,
    dTSup = 10.0,
    UACon = 3132.54953048,
    UAEva = 22163.5117527)

  annotation (
    defaultComponentPrefixes = "parameter",
    defaultComponentName="datHeaPum",
    preferredView="info",
  Documentation(info="<html>
<p>
Generated by M. Cimmino on 2017-01-26.
</p>
</html>"));