'''
This module contains the classes 
 - *Reader* that can be used to read ``*.mat`` files that have been generated by Dymola, 
 - *Reporter* that can be used to report to the standard output and standard error streams, and 
 - *Plotter* that contains method to plot results.
'''
