# Workflow for CI tests
name: CI-documentation-and-format

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, maint_*, release* ]
  pull_request:
    branches: [ master, maint_*, release* ]

# Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: Buildings

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test-formatting:
    # Skip if the commit message contains "ci skip"
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    runs-on: ubuntu-24.04

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12.3' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'      # optional x64 or x86. Defaults to x64 if not specified

      - name: "Install pip"
        run: pip3 install --upgrade pip

      - name: "Install BuildingsPy"
        run: pip3 install git+https://github.com/lbl-srg/BuildingsPy@v5.2.0

      - name: "Test user guide"
        run : (cd Resources/Documentation/userGuide; make regressiontest)

#      - name: "Test heat pump documentation"
#        run : (cd Resources/src/fluid/heatpumps/calibration/doc; make regressiontest)
